// Mission Learning OS — Execution Timer v1.1
// Stable timer: no MutationObserver and no DOM-wide render loop.
(() => {
  const KEY='missionOSState', ACTIVE='missionOSActiveSession';
  const PLANNED={'GE-01':60,'GE-02':60,'GE-03':60,'EN-GRAMMAR-01':50,'EN-GRAMMAR-02':50,'TECH-01':45,'TECH-02':45,'SYS-01':60,'SYS-02':60,'PY-01':60,'PY-02':60};
  const TITLES={'The Beginning of Geotechnical Engineering':'GE-01','Soil Mechanics — Three-Phase System':'GE-02','Soil Mechanics — Unit Weights':'GE-03','Present Simple':'EN-GRAMMAR-01','Present Continuous':'EN-GRAMMAR-02','Geotechnical Vocabulary Set 01':'TECH-01','Geotechnical Vocabulary Set 02':'TECH-02','System → Elements → Interconnections → Purpose':'SYS-01','Systems Thinking × Geotechnics':'SYS-02','Python — Session 1':'PY-01','Python — Session 2':'PY-02'};
  const load=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const mid=()=>TITLES[document.getElementById('mtitle')?.textContent?.trim()||'']||null;
  const elapsed=s=>!s?0:Number(s.accumulatedMs||0)+(s.status==='running'&&s.activeStartedAt?Date.now()-s.activeStartedAt:0);
  const fmt=ms=>{const t=Math.max(0,Math.floor(ms/1000)),h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
  function panel(){const modal=document.getElementById('modal'),detail=modal?.querySelector('.mission-detail');if(!modal?.classList.contains('open')||!detail)return null;let p=document.getElementById('executionTimerPanel');if(!p){p=document.createElement('div');p.id='executionTimerPanel';p.className='detail';detail.insertBefore(p,detail.firstChild)}return p}
  function render(){const p=panel();if(!p)return;const id=mid(),s=load(ACTIVE);if(!s){p.innerHTML='<b>Execution Timer</b><div class="dsub">Ready. Active study time only.</div><div class="actions" style="margin-top:10px"><button class="primary" id="execStartSafe">Start Mission</button></div>';p.querySelector('#execStartSafe').onclick=()=>start(id);return}if(s.id!==id){p.innerHTML='<b>Another Mission is running</b><div class="dsub">Open the running Mission to continue it.</div>';return}const paused=s.status==='paused';p.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><b>Execution Timer</b><span class="chip">${paused?'Paused':'Running'}</span></div><div id="execClock" style="font-size:38px;font-weight:800;margin:12px 0">${fmt(elapsed(s))}</div><div class="chips"><span class="chip">Planned ${s.plannedMinutes} min</span><span class="chip">Active only</span></div><div class="actions" style="margin-top:12px"><button class="${paused?'primary':'ghost'}" id="execPauseSafe">${paused?'Resume':'Pause'}</button><button class="ghost" id="execFinishSafe">Finish Mission</button></div>`;p.querySelector('#execPauseSafe').onclick=paused?resume:pause;p.querySelector('#execFinishSafe').onclick=finish}
  function start(id){if(!id)return;const s=load(ACTIVE);if(s){if(s.id===id)return;alert('A mission is already running. Open that Mission to continue it.');return}const now=Date.now();save(ACTIVE,{id,plannedMinutes:PLANNED[id]||60,startedAt:new Date(now).toISOString(),activeStartedAt:now,accumulatedMs:0,status:'running'});render()}
  function pause(){const s=load(ACTIVE);if(!s||s.status!=='running')return;s.accumulatedMs=elapsed(s);s.status='paused';delete s.activeStartedAt;save(ACTIVE,s);render()}
  function resume(){const s=load(ACTIVE);if(!s||s.status!=='paused')return;s.activeStartedAt=Date.now();s.status='running';save(ACTIVE,s);render()}
  function finish(){const s=load(ACTIVE);if(!s)return;if(!confirm('Finish this Mission and record the active study time?'))return;const ms=elapsed(s),state=load(KEY)||{};state.executionHistory=Array.isArray(state.executionHistory)?state.executionHistory:[];state.executionHistory.push({id:s.id,startedAt:s.startedAt,completedAt:new Date().toISOString(),plannedMinutes:s.plannedMinutes,actualMinutes:Math.round(ms/60000),activeMilliseconds:ms});save(KEY,state);localStorage.removeItem(ACTIVE);render()}
  function tick(){const modal=document.getElementById('modal'),open=modal?.classList.contains('open'),p=document.getElementById('executionTimerPanel');if(open&&!p)render();const s=load(ACTIVE),clock=document.getElementById('execClock');if(s&&clock&&s.status==='running')clock.textContent=fmt(elapsed(s))}
  window.missionOSExecutionHistory={version:'1.1',start,pause,resume,finish,render,active:()=>load(ACTIVE)};
  function boot(){setInterval(tick,500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();