// Mission Learning OS — Execution Control v2.0
// Execution Control owns ONLY the current-step timer. Mission Timer is independent.
(() => {
  const KEY='missionOSExecutionControlV2', GUIDE='missionOSGuideState';
  const TITLES={'GE-01':'The Beginning of Geotechnical Engineering','GE-02':'Soil Mechanics — Three-Phase System','GE-03':'Soil Mechanics — Unit Weights','EN-GRAMMAR-01':'Present Simple','EN-GRAMMAR-02':'Present Continuous','TECH-01':'Geotechnical Vocabulary Set 01','TECH-02':'Geotechnical Vocabulary Set 02','SYS-01':'System → Elements → Interconnections → Purpose','SYS-02':'Systems Thinking × Geotechnics','PY-01':'Python — Session 1','PY-02':'Python — Session 2'};
  const STEPS={'GE-01':[['Activate prior knowledge',5],['Focused reading',20],['Extract the model',15],['Active recall',10],['Build the deliverable',10]],'GE-02':[['Recall GE-01',5],['Learn the three-phase model',20],['Build relationships',20],['Active recall',10],['Deliverable',5]],'GE-03':[['Recall the phase model',5],['Learn unit weights',20],['Work examples',20],['Retrieval',10],['Deliverable',5]],'EN-GRAMMAR-01':[['Input',10],['Notice',10],['Controlled practice',15],['Retrieval',10],['Deliverable',5]],'EN-GRAMMAR-02':[['Recall',5],['Input',10],['Contrast',10],['Practice',20],['Production',5]],'TECH-01':[['Collect',10],['Define',10],['Contextualize',10],['Retrieve',10],['Deliverable',5]],'TECH-02':[['Collect',10],['Define',10],['Context',10],['Retrieve',10],['Deliverable',5]],'SYS-01':[['Learn the four ideas',15],['Choose a case',10],['Map it',20],['Check the model',10],['Deliverable',5]],'SYS-02':[['Select the engineering problem',10],['Map elements',15],['Map connections',15],['Test the system',15],['Deliverable',5]],'PY-01':[['Watch',10],['Pause and type',20],['Modify',10],['Solve',15],['Artifact',5]],'PY-02':[['Recall',5],['Watch',10],['Type and run',20],['Modify and solve',20],['Artifact',5]]};
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return{}}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const missionId=()=>{const t=document.getElementById('mtitle')?.textContent?.trim()||'';return Object.keys(TITLES).find(k=>TITLES[k]===t)||null};
  const get=id=>{const a=read(KEY);a[id]=a[id]||{started:false,paused:false,stepStartedAt:null,stepElapsed:0,finished:false};return{all:a,s:a[id]}};
  const progress=id=>{const st=read(GUIDE)[id]||{},list=STEPS[id]||[];let current=list.findIndex((_,i)=>!st[i]);if(current<0)current=Math.max(0,list.length-1);const done=list.filter((_,i)=>!!st[i]).length;return{list,current,done,pct:list.length?Math.round(done/list.length*100):0}};
  const elapsed=s=>Math.max(0,Number(s.stepElapsed)||0)+(s.stepStartedAt&&!s.paused&&!s.finished?Date.now()-s.stepStartedAt:0);
  const fmt=ms=>{const n=Math.floor(ms/1000),m=Math.floor(n/60),s=n%60;return`${m}:${String(s).padStart(2,'0')}`};
  function start(id){const {all,s}=get(id);if(s.finished)return;const first=!s.started;s.started=true;s.paused=false;s.stepStartedAt=Date.now();s.stepElapsed=first?0:s.stepElapsed;if(first){window.missionOSExecutionHistory?.start?.(id,(STEPS[id]||[]).reduce((n,x)=>n+Number(x[1]||0),0));window.missionOSDaily?.start?.(id);}write(KEY,all);render();}
  function pause(id){const {all,s}=get(id);if(!s.started||s.paused||s.finished)return;s.stepElapsed=elapsed(s);s.stepStartedAt=null;s.paused=true;write(KEY,all);render();}
  function resume(id){const {all,s}=get(id);if(!s.started||!s.paused||s.finished)return;s.paused=false;s.stepStartedAt=Date.now();write(KEY,all);render();}
  function finishStep(id){const {all,s}=get(id);if(!s.started||s.paused||s.finished)return;const p=progress(id),g=read(GUIDE);g[id]=g[id]||{};g[id][p.current]=true;write(GUIDE,g);const next=progress(id);if(next.done>=next.list.length){s.stepElapsed=elapsed(s);s.stepStartedAt=null;s.paused=true;s.finished=true;write(KEY,all);window.missionOSExecutionHistory?.finish?.();window.missionOSDaily?.completed?.(id);}else{s.stepElapsed=0;s.stepStartedAt=Date.now();s.paused=false;s.finished=false;s.step=p.current+1;write(KEY,all);}window.missionOSExecutionGuide?.render?.(true);render();}
  function render(){const modal=document.getElementById('modal'),detail=document.querySelector('.mission-detail'),id=missionId();if(!modal?.classList.contains('open')||!detail||!id)return;let p=document.getElementById('executionEnginePanel');if(!p){p=document.createElement('div');p.id='executionEnginePanel';p.className='detail';detail.appendChild(p)}const {s}=get(id),g=progress(id),x=g.list[g.current]||['Done',0],running=s.started&&!s.paused&&!s.finished;const controls=!s.started?'<button class="primary" data-ec="start">Start execution</button>':running?'<button class="ghost" data-ec="pause">Pause step</button>':'<button class="primary" data-ec="resume">Continue</button>';p.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><div><b>Execution Control</b><div class="dsub">Step timer مستقل از Mission Timer است.</div></div><span class="chip" dir="ltr">${g.done}/${g.list.length}</span></div><div style="margin:12px 0 7px;display:flex;justify-content:space-between"><strong dir="ltr">Step ${g.current+1} — ${x[0]}</strong><span dir="ltr">${x[1]} min</span></div><div class="progress"><div class="bar" style="width:${g.pct}%"></div></div><div id="engineClock" dir="ltr" style="font-size:28px;font-weight:800;margin:12px 0 5px">${fmt(elapsed(s))}</div><div class="dsub">فقط Start اولیه، این تایمر و Mission Timer را همزمان آغاز می‌کند.</div><div class="actions" style="margin-top:12px">${controls}<button class="ghost" data-ec="finish" ${running?'':'disabled'}>${g.current===g.list.length-1?'Finish step & Mission':'Finish step'}</button></div>`;}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-ec]');if(!b)return;const id=missionId();if(!id)return;e.preventDefault();const a=b.dataset.ec;if(a==='start')start(id);if(a==='pause')pause(id);if(a==='resume')resume(id);if(a==='finish')finishStep(id);},false);
  function tick(){const id=missionId(),c=document.getElementById('engineClock');if(!id||!c)return;c.textContent=fmt(elapsed(get(id).s));}
  function boot(){render();setInterval(tick,1000);setInterval(()=>{if(missionId())render()},3000)}
  window.missionOSExecutionEngine={version:'2.0',start,pause,resume,completeStep:finishStep,render};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
