// Mission Learning OS — Execution Guide v0.3
// Focused step-by-step execution inside the Mission modal.
(() => {
  const STATE_KEY='missionOSGuideState';
  const titles={'GE-01':'The Beginning of Geotechnical Engineering','GE-02':'Soil Mechanics — Three-Phase System','GE-03':'Soil Mechanics — Unit Weights','EN-GRAMMAR-01':'Present Simple','EN-GRAMMAR-02':'Present Continuous','TECH-01':'Geotechnical Vocabulary Set 01','TECH-02':'Geotechnical Vocabulary Set 02','SYS-01':'System → Elements → Interconnections → Purpose','SYS-02':'Systems Thinking × Geotechnics','PY-01':'Python — Session 1','PY-02':'Python — Session 2'};
  const guides={
    'GE-01':[['Activate prior knowledge',5,'Before opening the source, write 3–5 lines answering: What is soil? Why is soil an engineering material?'],['Focused reading',20,'Read the assigned section of Das & Sobhan, Chapter 1. Mark definitions, core ideas, and one engineering example.'],['Extract the model',15,'Write the 5 most important ideas in your own words and why each matters to a geotechnical engineer.'],['Active recall',10,'Close the book and answer the completion questions without looking.'],['Build the deliverable',10,'Create one compact knowledge card and the 5 active-recall questions.']],
    'GE-02':[['Recall GE-01',5,'Without notes, explain why soil needs an engineering model.'],['Learn the three-phase model',20,'Study solids, water and air and draw the phase diagram yourself.'],['Build relationships',20,'Learn void ratio, porosity, degree of saturation and water content and explain their physical meaning.'],['Active recall',10,'Redraw the three-phase diagram from memory and explain each ratio.'],['Deliverable',5,'Finish one annotated three-phase diagram and relationship sheet.']],
    'GE-03':[['Recall the phase model',5,'Redraw the three-phase system and identify what changes when air or water changes.'],['Learn unit weights',20,'Study total, dry, saturated and submerged unit weights. Focus on physical meaning before formulas.'],['Work examples',20,'Solve assigned examples and explain what each result means physically.'],['Retrieval',10,'Write formulas from memory and explain when each is appropriate.'],['Deliverable',5,'Create a solved calculation set and formula/meaning sheet.']],
    'EN-GRAMMAR-01':[['Input',10,'Study Present Simple: form, use and signal words.'],['Notice',10,'Study examples and identify why Present Simple is used.'],['Controlled practice',15,'Complete exercises without checking answers, then correct mistakes and explain why.'],['Retrieval',10,'Explain the rule aloud and create 5 original examples.'],['Deliverable',5,'Save exercises and your 5 original sentences.']],
    'EN-GRAMMAR-02':[['Recall',5,'Explain Present Simple from memory and give 3 examples.'],['Input',10,'Study Present Continuous: form, meaning and uses.'],['Contrast',10,'Compare Present Simple and Present Continuous using paired examples.'],['Practice',20,'Complete exercises, then correct and explain mistakes.'],['Production',5,'Write 5 original sentences mixing both tenses correctly.']],
    'TECH-01':[['Collect',10,'Select 10 useful geotechnical terms from the GE-01 reading.'],['Define',10,'Write a plain-English meaning for each term in your own words.'],['Contextualize',10,'Add one technical example sentence for every term.'],['Retrieve',10,'Hide meanings and test yourself on all 10 terms.'],['Deliverable',5,'Create 10 Anki-ready cards: term → meaning → example.']],
    'TECH-02':[['Collect',10,'Extract 10 new terms from the current soil-mechanics reading.'],['Define',10,'Write concise meanings in your own words.'],['Context',10,'Write engineering examples showing real usage.'],['Retrieve',10,'Test yourself without looking at meanings.'],['Deliverable',5,'Create 10 Anki-ready cards and use at least 5 terms in original sentences.']],
    'SYS-01':[['Learn the four ideas',15,'Study System, Elements, Interconnections and Purpose and define each.'],['Choose a case',10,'Pick one concrete geotechnical problem.'],['Map it',20,'Identify system boundary, elements, connections and purpose.'],['Check the model',10,'Ask what you left outside and which connection matters most.'],['Deliverable',5,'Create one system map and explain it in 5–8 sentences.']],
    'SYS-02':[['Select the engineering problem',10,'Choose a real geotechnical problem with interacting technical and contextual factors.'],['Map elements',15,'List soil, structure, water, loads, construction, monitoring and other relevant elements.'],['Map connections',15,'Draw important cause-and-effect or information relationships.'],['Test the system',15,'Change one element mentally and trace what else would change.'],['Deliverable',5,'Produce the system map and explain the most important interaction.']],
    'PY-01':[['Watch',10,'Watch the assigned lesson once for the big picture. Do not code yet.'],['Pause and type',20,'Replay in short sections. Type every example yourself and run it.'],['Modify',10,'Change at least two values or lines and run them again.'],['Solve',15,'Complete one small exercise without looking at the solution.'],['Artifact',5,'Save the working code and explain every new concept.']],
    'PY-02':[['Recall',5,'Without reopening Session 1, write what it taught you.'],['Watch',10,'Watch the new session once for the overall flow.'],['Type and run',20,'Replay in short sections, type every example and run it.'],['Modify and solve',20,'Change one example and solve one small exercise independently.'],['Artifact',5,'Save the code and explain the new concepts.']]
  };
  const generic=[['Orient',5,'Read the Mission goal, why it matters, prerequisite and deliverable.'],['Learn',25,'Work through the assigned source actively and focus on the Mission concepts.'],['Process',15,'Close the source and reconstruct the main ideas in your own words.'],['Retrieve',10,'Test yourself without looking at the source.'],['Deliverable',5,'Complete the deliverable and verify it against the completion check.']];
  const read=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{return{}}};
  const write=x=>localStorage.setItem(STATE_KEY,JSON.stringify(x));
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  let lastId='';
  function currentId(){const modal=document.getElementById('modal'),title=document.getElementById('mtitle')?.textContent?.trim();if(!modal?.classList.contains('open')||!title)return null;return Object.keys(titles).find(id=>titles[id]===title)||null;}
  function render(force=false){const id=currentId();if(!id)return;if(!force&&id===lastId&&document.getElementById('executionGuidePanel'))return;lastId=id;const detail=document.querySelector('.mission-detail');if(!detail)return;let panel=document.getElementById('executionGuidePanel');if(!panel){panel=document.createElement('div');panel.id='executionGuidePanel';panel.className='detail';detail.appendChild(panel)}const steps=guides[id]||generic,st=read(),done=st[id]||{},firstOpen=steps.findIndex((_,i)=>!done[i]),current=firstOpen<0?steps.length-1:firstOpen,completed=steps.filter((_,i)=>done[i]).length,pct=Math.round(completed/steps.length*100);panel.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><b>Execution Guide</b><div class="dsub">Step ${Math.min(current+1,steps.length)} of ${steps.length}</div></div><span class="chip">${completed}/${steps.length}</span></div><div class="progress" style="margin:10px 0 14px"><div class="bar" style="width:${pct}%"></div></div><div class="guideSteps">${steps.map((x,i)=>{const isDone=!!done[i],open=i===current&&!isDone;return `<label class="guideStep" style="display:flex;gap:10px;align-items:flex-start;padding:11px 0;border-bottom:1px solid var(--line);opacity:${isDone?.58:1}"><input style="margin-top:3px;width:18px;height:18px;accent-color:var(--accent)" type="checkbox" data-guide-step="${i}" ${isDone?'checked':''}><span style="flex:1"><strong style="display:block">Step ${i+1} — ${esc(x[0])}</strong><small style="display:block;color:var(--muted);margin-top:4px;line-height:1.5">${open?`${x[1]} min · ${esc(x[2])}`:isDone?'Completed':`${x[1]} min · Next`}</small></span></label>`}).join('')}</div>${completed===steps.length?'<div class="dsub" style="margin-top:12px">All steps complete. Finish the Mission when the deliverable is ready.</div>':''}`;
    panel.querySelectorAll('input').forEach(input=>input.addEventListener('change',e=>{const s=read();s[id]=s[id]||{};s[id][e.target.dataset.guideStep]=e.target.checked;write(s);render(true)}));
  }
  const boot=()=>{const modal=document.getElementById('modal');if(modal)new MutationObserver(()=>render()).observe(modal,{attributes:true,attributeFilter:['class'],childList:true,subtree:true});setInterval(()=>{if(!document.getElementById('modal')?.classList.contains('open'))lastId='';render()},500)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();