// Mission Learning OS — Execution Timer v1.2
// Stable, isolated timer. No MutationObserver. No DOM-wide render loop.
(() => {
  const KEY='missionOSState', ACTIVE='missionOSActiveSession';
  const PLANNED={'GE-01':60,'GE-02':60,'GE-03':60,'EN-GRAMMAR-01':50,'EN-GRAMMAR-02':50,'TECH-01':45,'TECH-02':45,'SYS-01':60,'SYS-02':60,'PY-01':60,'PY-02':60};
  const TITLES={'The Beginning of Geotechnical Engineering':'GE-01','Soil Mechanics — Three-Phase System':'GE-02','Soil Mechanics — Unit Weights':'GE-03','Present Simple':'EN-GRAMMAR-01','Present Continuous':'EN-GRAMMAR-02','Geotechnical Vocabulary Set 01':'TECH-01','Geotechnical Vocabulary Set 02':'TECH-02','System → Elements → Interconnections → Purpose':'SYS-01','Systems Thinking × Geotechnics':'SYS-02','Python — Session 1':'PY-01','Python — Session 2':'PY-02'};
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const title=id=>Object.keys(TITLES).find(k=>TITLES[k]===id)||id;
  const idFromModal=()=>TITLES[document.getElementById('mtitle')?.textContent?.trim()||'']||null;
  const elapsed=s=>!s?0:Number(s.accumulatedMs||0)+(s.status==='running'&&s.activeStartedAt?Date.now()-Date.parse(s.activeStartedAt):0);
  const fmt=ms=>{const t=Math.max(0,Math.floor(ms/1000)),h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
  function current(){const s=read(ACTIVE);if(!s)return null;if(!s.id||!s.status)return null;return s}
  function start(id){if(!id)return;if(current()){alert('A mission is already running. Open it to continue.');return}const now=new Date().toISOString();save(ACTIVE,{id,plannedMinutes:PLANNED[id]||60,startedAt:now,activeStartedAt:now,accumulatedMs:0,status:'running'});render()}
  function pause(){const s=current();if(!s||s.status!=='running')return;s.accumulatedMs=elapsed(s);s.status='paused';s.activeStartedAt=null;save(ACTIVE,s);render()}
  function resume(){const s=current();if(!s||s.status!=='paused')return;s.status='running';s.activeStartedAt=new Date().toISOString();save(ACTIVE,s);render()}
  function finish(){const s=current();if(!s)return;if(!confirm('Finish this Mission and record active study time?'))return;const ms=elapsed(s),state=read(KEY)||{};state.executionHistory=Array.isArray(state.executionHistory)?state.executionHistory:[];state.executionHistory.push({id:s.id,startedAt:s.startedAt,completedAt:new Date().toISOString(),plannedMinutes:s.plannedMinutes,actualMinutes:Math.round(ms/60000),activeMilliseconds:ms});save(KEY,state);localStorage.removeItem(ACTIVE);render();renderHistory()}
  function panel(){const modal=document.getElementById('modal'),detail=modal?.querySelector('.mission-detail');if(!modal?.classList.contains('open')||!detail)return null;let p=document.getElementById('executionTimerPanel');if(!p){p=document.createElement('div');p.id='executionTimerPanel';p.className='detail';detail.insertBefore(p,detail.firstChild)}return p}
  function render(){const p=panel();if(!p)return;const id=idFromModal(),s=current();if(!s){p.innerHTML='<b>Execution Timer</b><div class="dsub">Ready. Active study time only.</div><div class="actions" style="margin-top:10px"><button class="primary" id="execStart">Start Mission</button></div>';p.querySelector('#execStart').onclick=()=>start(id);return}if(s.id!==id){p.innerHTML=`<b>Another Mission is running</b><div class="dsub">${title(s.id)} · ${fmt(elapsed(s))} active</div><div class="actions" style="margin-top:10px"><button class="ghost" id="execOpenRunning">Open running Mission</button></div>`;p.querySelector('#execOpenRunning').onclick=()=>{document.querySelector(`[data-runtime-id="${s.id}"]`)?.click()};return}const paused=s.status==='paused';p.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><div><b>Execution Timer</b><div class="dsub">Active study time</div></div><span class="chip">${paused?'Paused':'Running'}</span></div><div id="execClock" style="font-size:38px;font-weight:800;margin:12px 0">${fmt(elapsed(s))}</div><div class="chips"><span class="chip">Planned ${s.plannedMinutes} min</span><span class="chip">Active only</span></div><div class="actions" style="margin-top:12px"><button class="${paused?'primary':'ghost'}" id="execPause">${paused?'Resume':'Pause'}</button><button class="ghost" id="execFinish">Finish Mission</button></div>`;p.querySelector('#execPause').onclick=()=>paused?resume():pause();p.querySelector('#execFinish').onclick=finish}
  function tick(){const s=current(),clock=document.getElementById('execClock');if(clock&&s&&s.status==='running')clock.textContent=fmt(elapsed(s))}
  function renderHistory(){const review=document.getElementById('review');if(!review)return;let p=document.getElementById('executionHistoryPanel');if(!p){p=document.createElement('div');p.id='executionHistoryPanel';p.className='panel';p.style.marginTop='18px';const g=review.querySelector('.grid');if(g)g.insertAdjacentElement('afterend',p)}const h=Array.isArray((read(KEY)||{}).executionHistory)?(read(KEY)||{}).executionHistory:[];p.innerHTML=h.length?`<h2>Execution History</h2><div class="statgrid"><div class="stat"><div class="num">${h.length}</div><div class="label">Sessions</div></div><div class="stat"><div class="num">${h.reduce((n,x)=>n+Number(x.actualMinutes||0),0)}m</div><div class="label">Active time</div></div></div>`:'<h2>Execution History</h2><div class="empty">No completed execution sessions recorded yet.</div>'}
  window.missionOSExecutionHistory={version:'1.2',start,pause,resume,finish,render,active:current};
  function boot(){render();renderHistory();setInterval(tick,1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();