// Mission Learning OS — authoritative runtime v0.8
// Zero-decision execution: queue + completion + energy + spaced review + application readiness + dependencies + timeline urgency.
(() => {
  const KEY='missionOSState';
  const state=JSON.parse(localStorage.getItem(KEY)||'{}');
  state.done=Array.isArray(state.done)?state.done:[];
  state.errors=Array.isArray(state.errors)?state.errors:[];
  state.energy=Number.isFinite(Number(state.energy))?Number(state.energy):7;
  state.availableMinutes=Number.isFinite(Number(state.availableMinutes))?Number(state.availableMinutes):120;
  state.completedAt=state.completedAt&&typeof state.completedAt==='object'?state.completedAt:{};
  state.reviews=state.reviews&&typeof state.reviews==='object'?state.reviews:{};
  const MISSIONS=[
    {id:'GE-01',topic:'Geotechnical Engineering',order:1,type:'learn',title:'The Beginning of Geotechnical Engineering',subject:'Advanced Geotechnics',mins:35,energy:3,weight:5,deadline:'2027-09-22',depends:[],topicDeps:[],goal:'Study Das & Sobhan, Chapter 1 and build a compact knowledge base.',why:'This is the confirmed starting point of the geotechnical path.',pre:'None beyond basic study readiness.',next:'Move into the next confirmed geotechnical foundation unit.',deliver:'Short summary + 5 active-recall questions.',check:'Explain the chapter without looking at the book.'},
    {id:'EN-GRAMMAR-01',topic:'Grammar',order:2,type:'practice',title:'Present Simple',subject:'General English',mins:30,energy:2,weight:5,deadline:'2027-09-22',depends:[],topicDeps:[],goal:'Learn and practice Present Simple from English Grammar in Use.',why:'It is the first confirmed unit of the grammar sequence and contributes to language readiness.',pre:'Basic sentence structure.',next:'Present Continuous.',deliver:'Completed exercises + 5 original sentences.',check:'Choose Present Simple correctly in new examples.'},
    {id:'TECH-01',topic:'Technical English',order:3,type:'learn',title:'Geotechnical Vocabulary Set 01',subject:'Technical English',mins:20,energy:2,weight:4,deadline:'2027-09-22',depends:['GE-01'],topicDeps:['Geotechnical Engineering'],goal:'Extract useful technical terms from today’s geotechnical reading.',why:'Technical English must grow from real geotechnical content.',pre:'The geotechnical reading mission.',next:'Vocabulary Set 02 from the next relevant reading.',deliver:'10 Anki-ready cards: term → meaning → example.',check:'10 usable cards are written.'},
    {id:'SYS-01',topic:'Systems Thinking',order:4,type:'research',title:'System → Elements → Interconnections → Purpose',subject:'Systems Thinking',mins:30,energy:3,weight:3,deadline:'2027-09-22',depends:[],topicDeps:[],goal:'Understand the four concepts and apply them to a geotechnical system.',why:'Systems Thinking is a confirmed cross-cutting competency.',pre:'None.',next:'A Systems Thinking × Geotechnics application.',deliver:'One note mapping the four concepts to a geotechnical problem.',check:'All four concepts are identified and connected to the case.'},
    {id:'PY-01',topic:'Python',order:5,type:'eng',title:'Python — Session 1',subject:'Data Analysis',mins:35,energy:3,weight:4,deadline:'2027-09-22',depends:[],topicDeps:[],goal:'Follow Jadi’s first Python session using Watch → Pause → Type → Run.',why:'Python is a confirmed Digital Geotechnics skill and part of the application-core foundation.',pre:'None.',next:'Session 2 at the real course pace.',deliver:'Run the session exercises + one tiny program.',check:'Code runs and every line can be explained.'}
  ];
  const INTERVALS=[1,3,7,14,30];
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const now=()=>new Date();
  const key=d=>new Date(d).toISOString().slice(0,10);
  const days=d=>Math.ceil((new Date(d)-now())/86400000);
  const missionDoneForTopic=topic=>MISSIONS.some(m=>m.topic===topic&&state.done.includes(m.id));
  const dependencyMap=()=>window.missionOSApplicationDependencies;
  const dependencyTopicsFor=m=>m.topicDeps?.length?m.topicDeps:(dependencyMap()?.getPrerequisites?.(m.topic)||[]);
  const dependencyReady=m=>dependencyTopicsFor(m).every(topic=>missionDoneForTopic(topic));
  const ready=m=>!state.done.includes(m.id)&&(m.depends||[]).every(x=>state.done.includes(x))&&dependencyReady(m);
  const blockedBy=m=>dependencyTopicsFor(m).filter(topic=>!missionDoneForTopic(topic));
  const profile=()=>state.energy>=8?{name:'high',limit:4,cap:150}:state.energy>=5?{name:'normal',limit:4,cap:120}:state.energy>=3?{name:'low',limit:3,cap:75}:{name:'recovery',limit:2,cap:45};
  const policyFor=m=>window.missionOSApplicationCore?.getDomainPolicy?.(m.subject)||'not_yet_classified';
  const timelineUrgency=m=>{const t=window.missionOSTimeline;if(!t||policyFor(m)!=='required_before_application')return 0;return t.urgency?.(t.applicationTarget)||0;};
  const score=m=>{
    if(m.isReview)return 80+(m.priorityBoost||0);
    if(!ready(m))return -1e9;
    let s=25+(m.weight||0)*4;
    const d=days(m.deadline);
    if(d<=7)s+=45;else if(d<=30)s+=32;else if(d<=90)s+=20;else if(d<=180)s+=10;
    const policy=policyFor(m);
    if(policy==='required_before_application')s+=28+timelineUrgency(m);
    else if(policy==='deepening_after_application')s-=12;
    else s+=8;
    if(m.energy<=state.energy)s+=8;else s-=(m.energy-state.energy)*5;
    return s;
  };
  function ensureReviewPlan(id){if(!state.completedAt[id]||state.reviews[id])return;const completed=new Date(state.completedAt[id]);state.reviews[id]={intervals:INTERVALS.map((interval,i)=>{const due=new Date(completed);due.setDate(due.getDate()+interval);return {reviewNumber:i+1,intervalDays:interval,dueDate:key(due),status:'pending'};})};}
  function dueReviews(){const debug=new URLSearchParams(location.search).get('reviewDebug')==='1';const out=[];for(const m of MISSIONS){ensureReviewPlan(m.id);const plan=state.reviews[m.id];if(!plan)continue;plan.intervals.forEach(r=>{if(r.status==='pending'&&(debug||r.dueDate<=key(now())))out.push({id:`REVIEW-${m.id}-${r.reviewNumber}`,isReview:true,sourceId:m.id,reviewNumber:r.reviewNumber,order:m.order,type:'review',title:`Review ${r.reviewNumber}: ${m.title}`,subject:m.subject,mins:Math.min(20,Math.max(10,Math.round(m.mins*.4))),energy:Math.min(4,m.energy||2),weight:10,priorityBoost:r.dueDate<key(now())?20:12,dueDate:r.dueDate,goal:`Retrieve the key ideas from ${m.title} without rereading first.`,why:`Scheduled spaced review (${r.intervalDays}-day interval).`,pre:'The source Mission is completed.',next:r.reviewNumber<5?`Next review in ${INTERVALS[r.reviewNumber]} days.`:'Continue retrieval only when the Director schedules it.',deliver:'Brief recall: explain the key ideas and answer the original completion check.',check:'You can explain the key ideas without looking at the source.'});});}return out;}
  function buildQueue(){const p=profile();const cap=Math.min(p.cap,Math.max(0,state.availableMinutes));const candidates=[...MISSIONS.filter(ready),...dueReviews()];const ranked=candidates.map(m=>({...m,priority:score(m),applicationPolicy:policyFor(m)})).sort((a,b)=>b.priority-a.priority||a.order-b.order);const q=[];let used=0;for(const m of ranked){if(q.length>=p.limit)break;if(m.energy>state.energy+1)continue;const mins=p.name==='low'?Math.min(25,m.mins):p.name==='recovery'?Math.min(20,m.mins):m.mins;if(used+mins>cap)continue;q.push({...m,mins});used+=mins;}return {q,used,p,cap};}
  function completeMission(m){if(m.isReview){const plan=state.reviews[m.sourceId];const r=plan?.intervals.find(x=>x.reviewNumber===m.reviewNumber);if(r)r.status='completed';save();render();toast('Review completed. Queue recalculated.');return;}if(!state.done.includes(m.id))state.done.push(m.id);state.completedAt[m.id]=now().toISOString();ensureReviewPlan(m.id);save();render();toast('Completed. Reviews scheduled. Queue recalculated.');}
  function render(){const {q,used,p}=buildQueue();const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v;};set('coreCount',q.length);set('queueCount',`${q.length} Core Missions · ${p.name}`);set('remaining',`${used}m`);set('done',state.done.length);set('pct',`${Math.round(state.done.length/MISSIONS.length*100)}%`);const bar=document.getElementById('bar');if(bar)bar.style.width=`${Math.round(state.done.length/MISSIONS.length*100)}%`;const list=document.getElementById('missionList');if(list)list.innerHTML=q.length?q.map(card).join(''):'<div class="empty">Today’s executable queue is complete.</div>';const all=document.getElementById('allMissions');if(all)all.innerHTML=MISSIONS.filter(m=>!state.done.includes(m.id)).map(m=>card({...m,priority:score(m),blockedBy:blockedBy(m)})).join('');const obj=document.getElementById('objective');if(obj)obj.textContent=p.name==='recovery'?'Minimum viable progress. Keep the chain alive.':p.name==='low'?'Light workload. Execute without redesigning the plan.':'Follow the queue. The Director has already decided what comes next.';const today=document.getElementById('today');if(today)today.textContent=now().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});renderReviewSummary();}
  function card(m){const policy=m.applicationPolicy||policyFor(m);const badge=policy==='required_before_application'?' · application core':policy==='deepening_after_application'?' · deepening later':'';const blocked=m.blockedBy?.length?`<div class="mission-meta">Blocked by: ${m.blockedBy.join(', ')}</div>`:'';return `<div class="mission" data-runtime-id="${m.id}"><div class="dot ${m.type}"></div><div class="mission-main"><div class="mission-title">${m.title}</div><div class="mission-meta">${m.subject} · ${m.mins} min · ${m.energy}/10 energy${m.isReview?' · due '+m.dueDate:''}${badge}</div>${blocked}</div><span class="score">Priority ${Math.round(m.priority||0)}</span></div>`;}
  function openMission(m){const ids=['mtitle','mgoal','mwhy','mpre','mnext','mdeliver','mchecktext'];const vals=[m.title,m.goal,m.why,m.pre,m.next,m.deliver,m.check];ids.forEach((id,i)=>{const e=document.getElementById(id);if(e)e.textContent=vals[i]});const check=document.getElementById('mcheck');if(check)check.checked=false;const btn=document.getElementById('completeBtn');if(btn)btn.onclick=()=>{if(!check?.checked){toast('Complete the deliverable first.');return;}completeMission(m);document.getElementById('modal')?.classList.remove('open');};document.getElementById('modal')?.classList.add('open');}
  function renderReviewSummary(){const due=dueReviews();const root=document.getElementById('reviewQueue');if(root)root.innerHTML=due.length?due.map(r=>`<div class="mission" data-runtime-id="${r.id}"><div class="mission-main"><div class="mission-title">${r.title}</div><div class="mission-meta">${r.subject} · ${r.mins} min · due ${r.dueDate}</div></div><span class="score">Due</span></div>`).join(''):'<div class="empty">No reviews due.</div>';}
  function toast(t){const e=document.getElementById('toast');if(e){e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200);}}
  document.addEventListener('click',e=>{const energy=e.target.closest('#energyBtn');if(energy){e.preventDefault();e.stopImmediatePropagation();const v=window.prompt('Energy today (1–10):',String(state.energy));if(v!==null){const n=Number(v);if(Number.isFinite(n)){state.energy=Math.max(1,Math.min(10,n));save();render();const x=buildQueue();toast(`Energy ${state.energy}/10 · ${x.p.name} · ${x.q.length} Missions · ${x.used}m`);}}return;}const mission=e.target.closest('[data-runtime-id]');if(mission){e.preventDefault();e.stopImmediatePropagation();const m=MISSIONS.find(x=>x.id===mission.dataset.runtimeId)||dueReviews().find(x=>x.id===mission.dataset.runtimeId);if(m)openMission(m);}},true);
  const eb=document.getElementById('energyBtn');if(eb)eb.onclick=e=>{e.preventDefault();const v=window.prompt('Energy today (1–10):',String(state.energy));if(v!==null){const n=Number(v);if(Number.isFinite(n)){state.energy=Math.max(1,Math.min(10,n));save();render();const x=buildQueue();toast(`Energy ${state.energy}/10 · ${x.p.name} · ${x.q.length} Missions · ${x.used}m`);}}};
  const reset=document.getElementById('reset');if(reset)reset.onclick=()=>{state.done=[];state.completedAt={};state.reviews={};save();render();toast('Progress reset.');};
  render();
})();
